name: macOS Say Command

on: [push]

jobs:
  say-hello:
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run say command
        run: |
          say "Привет, Александр!" -o hello.aiff

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello.mp3
          path: hello.mp3
